notifier:
  enabled: true
  istio:
    enabled: false

idgenerator:
  enabled: true
  istio:
    enabled: false

ridgenerator:
  enabled: true
  istio:
    enabled: false

pridgenerator:
  enabled: true
  istio:
    enabled: false
